export default {
  renderer: ["render:webgl"],
  controls: [
    "controls:target",
    "controls:pointer",
    "controls:keyboard",
    "controls:gamepad",
    "controls:gyro",
  ],
  ui: [
    "ui:play-pause",
    "ui:volume",
    "ui:time",
    "ui:scrubber",
    "ui:repeat",
    "ui:fullscreen",
    "ui:stereo",
    "ui:vr",
    "ui:source",
    "ui:dial",
    "ui:loader",
    "ui:error",
  ],
  format: 360,
  stereo: false,
  autoSuspend: true,
  autoHideUI: true,
};
